/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/condition-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mission` | `/mission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/condition` | `/condition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal/setup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal/detail`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/condition-check`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mission` | `/mission`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/condition` | `/condition`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goal/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goal/detail`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/condition-check${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mission${`?${string}` | `#${string}` | ''}` | `/mission${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/condition${`?${string}` | `#${string}` | ''}` | `/condition${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manage${`?${string}` | `#${string}` | ''}` | `/manage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my${`?${string}` | `#${string}` | ''}` | `/my${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/profile${`?${string}` | `#${string}` | ''}` | `/onboarding/experience${`?${string}` | `#${string}` | ''}` | `/onboarding/goal/setup${`?${string}` | `#${string}` | ''}` | `/onboarding/goal/detail${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/condition-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mission` | `/mission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/condition` | `/condition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/experience`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal/setup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal/detail`; params?: Router.UnknownInputParams; };
    }
  }
}
